### ISSUE TITLE
Discontinue dependency on Themis subpackages

### ISSUE THREAD

**Issue by joe94** [xmidt-org/argus#175]
This work will be rather non-trivial and this issue can likely be split into smaller ones. One important thing to consider will be to ensure the OpenTelemetry tracing feature is present in the replacements of `xhttpserver` and `xhttpclient`.
Sub-tacks for this issue:
- [x] Switch to zap logger https://github.com/xmidt-org/argus/issues/181
- [x] Use arrange to unmarshal config structs https://github.com/xmidt-org/argus/issues/182
- [x] Use arrange servers https://github.com/xmidt-org/argus/issues/183
- [x] Add back tracing feature https://github.com/xmidt-org/argus/issues/184
